name: Capistrano Deploy
description: Deploy to staging and production using Capistrano

on:
  workflow_call:
    inputs:
      stage:
        description: "The stage to deploy to"
        required: true
        default: "staging"
      host:
        description: "The host to deploy to"
        required: false
      port:
        description: "The port to use"
        required: false

    secrets:
      DEPLOY-SSH-KEY:
        description: "The private key to use"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Setup ssh
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{inputs.host || secrets.HOST}}
          port: ${{inputs.port || secrets.PORT}}
          private_key: ${{inputs.ssh-key || secrets.DEPLOY-SSH-KEY}}

      - name: Deploy server
        run: |
          bundler exec cap ${{inputs.stage}} deploy
