on: [push]

jobs:
  git-head-commit:
    runs-on: self-hosted
    name: Get git head commit information
    steps:
      - name: Git head commit
        id: git-head-commit
        uses: fifteen1309/dotfiles/.github/actions/git-head-commit@main
      - name: Get outpush time
        run: echo "${{steps.git-head-commit.outputs.author_email}}"
