name: Test telegram notification

on: [push]

jobs:
  capistrano:
    uses: fifteen1309/dotfiles/.github/workflows/capistrano.yml@main
    with:
      stage: staging
      runs_on: self-hosted
      host: 12.21.212.12
      port: 22
    secrets:
      bot_token: "dasdasdasdasdasdasdasdasdas"
      group_id: -2312312312312
